import os
import sys
from pathlib import Path
from stylesheet import *

from guiUtils import *

from PyQt6.QtCore import QDir
from PyQt6 import QtCore, QtGui, QtWidgets

CURRENT_DIRECTORY = Path(__file__).resolve().parent

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        QDir.addSearchPath("images", os.fspath(CURRENT_DIRECTORY / "images"))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setMaximumSize(QtCore.QSize(1200, 800))
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        self.mainWindow = QtWidgets.QWidget(MainWindow)
        self.mainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.mainWindow.setStyleSheet(styleMainWindow)
        self.mainWindow.setObjectName("mainWindow")

        self.layoutWidget = QtWidgets.QWidget(self.mainWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(-4, 1, 1211, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.topLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.topLayout.setContentsMargins(0, 0, 0, 0)
        self.topLayout.setObjectName("topLayout")

        self.paragraphLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paragraphLabel.sizePolicy().hasHeightForWidth())
        self.paragraphLabel.setSizePolicy(sizePolicy)
        self.paragraphLabel.setMinimumSize(QtCore.QSize(64, 64))
        self.paragraphLabel.setMaximumSize(QtCore.QSize(64, 64))
        self.paragraphLabel.setBaseSize(QtCore.QSize(64, 64))
        self.pixmap = QtGui.QPixmap("images:paragraph.png")
        self.paragraphLabel.setPixmap(self.pixmap)
        self.paragraphLabel.resize(self.pixmap.width(), self.pixmap.height())
        self.paragraphLabel.setObjectName("paragraphLabel")
        self.paragraphLabel.setGeometry(QtCore.QRect(150, 80, 64, 64))
        
        self.labelName = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelName.sizePolicy().hasHeightForWidth())
        self.labelName.setSizePolicy(sizePolicy)
        self.labelName.setMaximumSize(QtCore.QSize(450, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.topLayout.addWidget(self.labelName, 0, 0, 1, 1)
        
        self.infoBtn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoBtn.sizePolicy().hasHeightForWidth())
        self.infoBtn.setSizePolicy(sizePolicy)
        self.infoBtn.setMinimumSize(QtCore.QSize(54, 54))
        self.infoBtn.setMaximumSize(QtCore.QSize(54, 54))
        self.infoBtn.setBaseSize(QtCore.QSize(54, 54))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.infoBtn.setFont(font)
        self.infoBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.infoBtn.setText("i")

        self.infoBtn.setFixedSize(54, 54)
        self.infoBtn.setObjectName("infoBtn")
        self.infoBtn.setStyleSheet(styleInfoButton)
        self.topLayout.addWidget(self.infoBtn, 0, 1, 1, 1)
        
        self.layoutWidget1 = QtWidgets.QWidget(self.mainWindow)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 220, 1201, 581))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.bottomLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.bottomLayout.setContentsMargins(0, 0, 0, 0)
        self.bottomLayout.setObjectName("bottomLayout")
       
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.typeLayout = QtWidgets.QHBoxLayout()
        self.typeLayout.setObjectName("typeLayout")
        
        self.typeLabel = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLabel.sizePolicy().hasHeightForWidth())
        self.typeLabel.setSizePolicy(sizePolicy)
        self.typeLabel.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.typeLabel.setFont(font)
        self.typeLabel.setAutoFillBackground(False)
        self.typeLabel.setObjectName("typeLabel")
        self.typeLabel.setStyleSheet(labelsFields)
        self.typeLayout.addWidget(self.typeLabel, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        
        self.scrollBarType = QtWidgets.QScrollBar()
        self.scrollBarType.setStyleSheet(scrollBarStyle)

        self.typeInput = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeInput.sizePolicy().hasHeightForWidth())
        self.typeInput.setSizePolicy(sizePolicy)
        self.typeInput.setMaximumSize(QtCore.QSize(400, 30))
        self.typeInput.setPlaceholderText('Typ dokumentu np. "Ustawa"')
        font = QtGui.QFont()
        self.typeInput.setFont(font)
        self.typeInput.setObjectName("typeInput")
        self.typeLayout.addWidget(self.typeInput)
        
        self.leftLayout.addLayout(self.typeLayout)
        self.positionLayout = QtWidgets.QHBoxLayout()
        self.positionLayout.setObjectName("positionLayout")
        self.positionLabel = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positionLabel.sizePolicy().hasHeightForWidth())
        self.positionLabel.setSizePolicy(sizePolicy)
        self.positionLabel.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.positionLabel.setFont(font)
        self.positionLabel.setObjectName("positionLabel")
        self.positionLabel.setStyleSheet(labelsFields)
        self.positionLayout.addWidget(self.positionLabel, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        
        self.positionInput = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positionInput.sizePolicy().hasHeightForWidth())
        self.positionInput.setSizePolicy(sizePolicy)
        self.positionInput.setMaximumSize(QtCore.QSize(1000, 30))
        self.positionInput.setPlaceholderText('Pozycja np. "1333"')
        self.positionInput.setObjectName("positionInput")
        self.positionLayout.addWidget(self.positionInput)
        self.leftLayout.addLayout(self.positionLayout)
        
        self.publisherLayout = QtWidgets.QHBoxLayout()
        self.publisherLayout.setObjectName("publisherLayout")
        self.publicationPlaceLabel = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.publicationPlaceLabel.sizePolicy().hasHeightForWidth())
        self.publicationPlaceLabel.setSizePolicy(sizePolicy)
        self.publicationPlaceLabel.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.publicationPlaceLabel.setFont(font)
        self.publicationPlaceLabel.setObjectName("publicationPlaceLabel")
        self.publicationPlaceLabel.setStyleSheet(labelsFields)
        self.publisherLayout.addWidget(self.publicationPlaceLabel, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        
        self.publicationPlaceDropDown = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.publicationPlaceDropDown.sizePolicy().hasHeightForWidth())
        self.publicationPlaceDropDown.setSizePolicy(sizePolicy)
        self.publicationPlaceDropDown.setMaximumSize(QtCore.QSize(400, 30))
        self.publicationPlaceDropDown.setStyleSheet(dropdownsStyle)
        self.publicationPlaceDropDown.setEditable(False)
        self.publicationPlaceDropDown.setObjectName("publicationPlaceDropDown")
        self.publicationPlaceDropDown.setPlaceholderText("Dziennik Ustaw i Monitor Polski")
        self.publicationPlaceDropDown.addItem("Dziennik Ustaw")
        self.publicationPlaceDropDown.addItem("Monitor Polski")
        self.publicationPlaceDropDown.addItem("Dziennik Ustaw i Monitor Polski")
        self.publicationPlaceDropDown.setMaxVisibleItems(11)
        self.publicationPlaceDropDown.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.publicationPlaceDropDown.view().setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)) # Set pointer to the content of dropdown  
        self.publisherLayout.addWidget(self.publicationPlaceDropDown)
        
        self.leftLayout.addLayout(self.publisherLayout)
        self.keywordsLayout = QtWidgets.QHBoxLayout()
        self.keywordsLayout.setObjectName("keywordsLayout")
        self.keywordsLabel = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keywordsLabel.sizePolicy().hasHeightForWidth())
        self.keywordsLabel.setSizePolicy(sizePolicy)
        self.keywordsLabel.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.keywordsLabel.setFont(font)
        self.keywordsLabel.setObjectName("keywordsLabel")
        self.keywordsLabel.setStyleSheet(labelsFields)
        self.keywordsLayout.addWidget(self.keywordsLabel, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        
        self.scrollBarKeywords = QtWidgets.QScrollBar()
        self.scrollBarKeywords.setStyleSheet(scrollBarStyle)

        self.keywordsInput = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keywordsInput.sizePolicy().hasHeightForWidth())
        self.keywordsInput.setSizePolicy(sizePolicy)
        self.keywordsInput.setMaximumSize(QtCore.QSize(500, 30))
        self.keywordsInput.setPlaceholderText('Słowa kluczowe np."nauczyciel"')
        self.keywordsInput.setObjectName("keywordsInput")
        self.keywordsLayout.addWidget(self.keywordsInput)
        self.leftLayout.addLayout(self.keywordsLayout)
        
        self.dateFromLayout = QtWidgets.QHBoxLayout()
        self.dateFromLayout.setObjectName("dateFromLayout")
        self.dateFromLabel = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateFromLabel.sizePolicy().hasHeightForWidth())
        self.dateFromLabel.setSizePolicy(sizePolicy)
        self.dateFromLabel.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dateFromLabel.setFont(font)
        self.dateFromLabel.setObjectName("dateFromLabel")
        self.dateFromLabel.setStyleSheet(labelsFields)
        self.dateFromLayout.addWidget(self.dateFromLabel, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        
        self.dateFromInput = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateFromInput.sizePolicy().hasHeightForWidth())
        self.dateFromInput.setSizePolicy(sizePolicy)
        self.dateFromInput.setMaximumSize(QtCore.QSize(500, 30))
        self.dateFromInput.setPlaceholderText('yyyy-MM-dd (rok-miesiąc-dzień) np. "2000-12-01"')
        self.dateFromInput.setObjectName("dateFromInput")
        self.dateFromLayout.addWidget(self.dateFromInput)
        self.leftLayout.addLayout(self.dateFromLayout)
        
        self.dateToLayout = QtWidgets.QHBoxLayout()
        self.dateToLayout.setObjectName("dateToLayout")
        self.dateToLabel = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateToLabel.sizePolicy().hasHeightForWidth())
        self.dateToLabel.setSizePolicy(sizePolicy)
        self.dateToLabel.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dateToLabel.setFont(font)
        self.dateToLabel.setObjectName("dateToLabel")
        self.dateToLabel.setStyleSheet(labelsFields)
        self.dateToLayout.addWidget(self.dateToLabel, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        
        self.dateToInput = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateToInput.sizePolicy().hasHeightForWidth())
        self.dateToInput.setSizePolicy(sizePolicy)
        self.dateToInput.setMaximumSize(QtCore.QSize(500, 30))
        self.dateToInput.setPlaceholderText('yyyy-MM-dd (rok-miesiąc-dzień) np. "2000-12-01"')
        self.dateToInput.setObjectName("dateToInput")
        self.dateToLayout.addWidget(self.dateToInput)
        self.leftLayout.addLayout(self.dateToLayout)
        
        self.yearLayout = QtWidgets.QHBoxLayout()
        self.yearLayout.setObjectName("yearLayout")
        self.yearLabel = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yearLabel.sizePolicy().hasHeightForWidth())
        self.yearLabel.setSizePolicy(sizePolicy)
        self.yearLabel.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.yearLabel.setFont(font)
        self.yearLabel.setObjectName("yearLabel")
        self.yearLabel.setStyleSheet(labelsFields)
        self.yearLayout.addWidget(self.yearLabel, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        
        self.yearInput = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yearInput.sizePolicy().hasHeightForWidth())
        self.yearInput.setSizePolicy(sizePolicy)
        self.yearInput.setMaximumSize(QtCore.QSize(500, 30))
        self.yearInput.setPlaceholderText('Rok wydania np."1999"')
        self.yearInput.setObjectName("yearInput")
        self.yearLayout.addWidget(self.yearInput)
        self.leftLayout.addLayout(self.yearLayout)
        
        self.searchBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.searchBtn.setMinimumSize(QtCore.QSize(110, 40))
        self.searchBtn.setMaximumSize(QtCore.QSize(110, 40))
        self.searchBtn.setBaseSize(QtCore.QSize(110, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.searchBtn.setFont(font)
        self.searchBtn.setObjectName("searchBtn")
        self.leftLayout.addWidget(self.searchBtn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.bottomLayout.addLayout(self.leftLayout)
        self.searchBtn.setStyleSheet(styleSearchButton)
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        
        self.scrollBarList = QtWidgets.QScrollBar()
        self.scrollBarList.setStyleSheet(scrollBarStyle)

        self.linkList = QtWidgets.QTextBrowser(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linkList.sizePolicy().hasHeightForWidth())
        self.linkList.setSizePolicy(sizePolicy)
        self.linkList.setMaximumSize(QtCore.QSize(600, 700))
        self.linkList.setStyleSheet("")
        self.linkList.setObjectName("linkList")
        self.linkList.setOpenExternalLinks(True)
        self.linkList.setVerticalScrollBar(self.scrollBarList)

        self.bottomLayout.addWidget(self.linkList)
        MainWindow.setCentralWidget(self.mainWindow)

        self.messageBox = QtWidgets.QMessageBox()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Method mapping
        Ui_MainWindow.onSearchClick = onSearchClick
        Ui_MainWindow.getTypeList = getTypeList
        Ui_MainWindow.getKeywordsList = getKeywordsList
        Ui_MainWindow.showMessageBox = showMessageBox

        # Fields init
        self.typeList = self.getTypeList()
        self.keywordsList = self.getKeywordsList()

        # Set completer for type field
        self.typeCompleter = QtWidgets.QCompleter(self.typeList)
        self.typeCompleter.popup().setStyleSheet(completerStyle)
        self.typeCompleter.popup().setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.typeCompleter.setCaseSensitivity(QtCore.Qt.CaseSensitivity.CaseInsensitive)
        self.typeCompleter.setMaxVisibleItems(8)
        self.typeCompleter.popup().setVerticalScrollBar(self.scrollBarType)
        self.typeInput.setCompleter(self.typeCompleter)

        # Set completer for keywords field
        self.keywordsCompleter = QtWidgets.QCompleter(self.keywordsList)
        self.keywordsCompleter.popup().setStyleSheet(completerStyle)
        self.keywordsCompleter.popup().setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.keywordsCompleter.setCaseSensitivity(QtCore.Qt.CaseSensitivity.CaseInsensitive)
        self.keywordsCompleter.setMaxVisibleItems(8)
        self.keywordsCompleter.popup().setVerticalScrollBar(self.scrollBarKeywords)
        self.keywordsInput.setCompleter(self.keywordsCompleter)

        # Methods mapping
        self.searchBtn.clicked.connect(self.onSearchClick)
        self.infoBtn.clicked.connect(self.showMessageBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelName.setText(_translate("MainWindow", "Wyszukiwarka aktów prawnych"))
        self.typeLabel.setText(_translate("MainWindow", "Typ dokumentu"))
        self.positionLabel.setText(_translate("MainWindow", "Pozycja"))
        self.publicationPlaceLabel.setText(_translate("MainWindow", "Miejsce publikacji"))
        self.keywordsLabel.setText(_translate("MainWindow", "Słowa kluczowe"))
        self.dateFromLabel.setText(_translate("MainWindow", "Data od"))
        self.dateToLabel.setText(_translate("MainWindow", "Data do"))
        self.yearLabel.setText(_translate("MainWindow", "Rok wydania"))
        self.searchBtn.setText(_translate("MainWindow", "Wyszukaj"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())